openapi: 3.0.1
info:
  title: Demo API
  version: v1
  description: |
    La API proporciona herramientas para interactuar con los siguientes recursos:
    
    - **Resultados** (`/api/results`): Permite visualizar los resultados de los juegos realizados por los usuarios.
    
    **Para acceder a cualquiera de los endpoints, es necesario autenticarse previamente y proporcionar el token en el encabezado de autorización.**

servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo local
  - url: https://lo-pokequiz.herokuapp.com
    description: Servidor en producción

components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
paths:
  /api/signin:
    post:
      summary: Create session
      tags:
        - Sign In
      parameters: []
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    properties:
                      id:
                        type: string
                        example: 10
                      jti:
                        type: string
                        example: d7257bee-b1b5-41b9-a757-58dc576f4b92

        401:
          description: El servidor no puede proporcionar acceso a la recurso solicitado porque no ha proporcionado las credenciales de acceso válidas o no tiene permiso para acceder.
        422:
          description: La solicitud estaba bien formada, pero no se pudo seguir debido a errores semánticos.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password
              required:
                - email
                - password

  /api/signup:
    post:
      summary: Create user
      tags:
        - Sign Up
      parameters: [ ]
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    properties:
                      username:
                        type: string
                        example: Jon Due
                      email:
                        type: string
                        example: user@example.com

        401:
          description: El servidor no puede proporcionar acceso a la recurso solicitado porque no ha proporcionado las credenciales de acceso válidas o no tiene permiso para acceder.
        422:
          description: La solicitud estaba bien formada, pero no se pudo seguir debido a errores semánticos.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  properties:
                    username:
                      type: string
                      example: JhonDue
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password
              required:
                - email
                - password


  /api/results:
    get:
      summary: List user results
      tags:
        - Game results
      security:
        - Bearer: [ ]
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        username:
                          type: string
                          example: "JhonDue"
                        games:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                              score:
                                type: integer
                                example: 0
                              finished:
                                type: boolean
                                example: true
                              quizzes:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                      example: 1
                                    question:
                                      type: string
                                      example: "No es precisamente rápido ni fuerte. Es el Pokémon más debilucho y simplón de todos los que hay."
                                    correct_answer:
                                      type: string
                                      example: "magikarp"
                                    user_answer:
                                      type: string
                                      example: "shellder"
        401:
          description: El servidor no puede proporcionar acceso a la recurso solicitado porque no ha proporcionado las credenciales de acceso válidas o no tiene permiso para acceder.


